name: sun-climate-bayes
channels:
  - conda-forge
dependencies:
  - numpy<2
  - xarray
  - colorcet
  - dask
  - dill
  - arviz
  - packaging
  - bottleneck
  - cftime
  - numbagg
  - netcdf4
  - matplotlib
  - seaborn
  - nc-time-axis
  - scipy
  - h5py
  - pyopencl
  - jpype1
  - networkx
  - ecos
  - prettytable
  - mpmath
  - cython
  - numba
  - cudatoolkit
  - cartopy
  - tqdm
  - ipywidgets
  - pip
  - pip:
    - tensorrt
    - tensorflow-probability
    - funsor
    - corner
    - graphviz
    - "jax[cuda12]"  
    - jaxns
