# Configuration for Precipitation Analysis

data:
  label: precip
  input_file: /d0/amunozj/precipitation_data/access/gpcp_v02r03.nc
  var_name: precip
  dimensions:
    lon: longitude # Dimension name for longitude
    lat: latitude  # Dimension name for latitude
    time: time     # Dimension name for time

processing:
  coarsen_levels: [8] # List of spatial coarsening factors
  smoothing: 30          # Temporal smoothing factor

execution:
  output_dir: /d0/amunozj/git_repos/interconnection-sun-climate/outputs/multipurpose # Base output directory
  workers: 2             # Number of parallel workers
  nested_sampler:
    max_samples: 40000
    num_posterior_samples: 5000

priors: # --- CRITICAL: Adjust based on expected variable scale (e.g., mm/day) ---
  sigma_scale: 5.0
  offset_mean: 2.0
  offset_std: 2.0
  seasonal_amp_mean: 1.0
  seasonal_amp_std: 2.0
  seasonal_exp_scale: 2.0
  co2_gain_mean: 0.0
  co2_gain_std: 1.0
  oni_gain_mean: 0.0
  oni_gain_std: 1.0
  oni_shift_mean: 0.0
  oni_shift_std: 0.5
  cr_gain_mean: 0.0
  cr_gain_std: 1.0
  cr_shift_mean: 0.0
  cr_shift_std: 1.0

external_data: # Optional: Paths to external datasets
  oni:
    file_path: /d0/amunozj/git_repos/interconnection-sun-climate/ENI/detrend.nino34.ascii.txt
  cr:
    file_path: /d0/amunozj/git_repos/interconnection-sun-climate/data/cosmic_rays/OULU_1964_05_01 _00_00_2024_10_28 _23_30.csv
    var_name: CorrectedCountRate # Variable name within the CR CSV file
