#!/bin/tcsh

# process GISTEMP v4

wget -nc --no-check-certificate https://data.giss.nasa.gov/gistemp/tabledata_v4/GLB.Ts+dSST.txt -O GLB.Ts+dSST_v4.txt

echo "Global-Mean Surface Temperature" > gistemp_v4_mon.txt
echo " " >> gistemp_v4_mon.txt
echo "Temperature Anomaly (\So\C)" >> gistemp_v4_mon.txt
echo "Year Monthly_Mean_(GHCN4)" >> gistemp_v4_mon.txt

tail +9 GLB.Ts+dSST_v4.txt | grep "[0-9]" | grep -v "[a-z]" | awk '{print $1+(1/24.) " " substr($0,6,5)/100. "\n" $1+(3/24.) " " substr($0,11,5)/100. "\n" $1+(5/24.) " "  substr($0,16,5)/100. "\n" $1+(7/24.) " "  substr($0,21,5)/100. "\n" $1+(9/24.) " "  substr($0,26,5)/100. "\n" $1+(11/24.) " "  substr($0,31,5)/100. "\n" $1+(13/24.) " "  substr($0,36,5)/100. "\n" $1+(15/24.) " "  substr($0,41,5)/100. "\n" $1+(17/24.) " "  substr($0,46,5)/100. "\n" $1+(19/24.) " "  substr($0,51,5)/100. "\n" $1+(21/24.) " "  substr($0,56,5)/100. "\n" $1+(23/24.) " "  substr($0,61,5)/100. }' | grep -v "\*\*" | awk '{if ($2 != 0 || $1 < 2010) print $0}' >> gistemp_v4_mon.txt

echo " " >> gistemp_v4_mon.txt

# ann mean

echo "Global-Mean Surface Temperature" > gistemp_v4_ann.txt
echo " " >> gistemp_v4_ann.txt
echo "Temperature Anomaly (\So\C)" >> gistemp_v4_ann.txt
echo "Year GISTEMP_Ann_(GHCN4)" >> gistemp_v4_ann.txt

tail +5 gistemp_v4_mon.txt | grep "[0-9]" | awk '{i=i+1 ; sum=sum+$2 ; yr=int($1) ; if (i == 12) {print yr " " sum/12. ; i=0 ; sum=0}} END{if ( i == 12) {print yr " " sum/i}}'>> gistemp_v4_ann.txt

echo " " >> gistemp_v4_ann.txt

